VirtoCommerce/vc-module-export

VirtoCommerce.ExportModule.CsvProvider/CsvExportProvider.cs, VirtoCommerce.ExportModule.CsvProvider/CsvProviderConfiguration.cs, VirtoCommerce.ExportModule.CsvProvider/EmptyClassMapImpl.cs, VirtoCommerce.ExportModule.CsvProvider/MetadataFilteredMap.cs, VirtoCommerce.ExportModule.CsvProvider/Properties/AssemblyInfo.cs, VirtoCommerce.ExportModule.CsvProvider/VirtoCommerce.ExportModule.CsvProvider.csproj, VirtoCommerce.ExportModule.CsvProvider/packages.config, VirtoCommerce.ExportModule.Data/Services/ExportPagedDataSource.cs, VirtoCommerce.ExportModule.Data/Services/ExportedTypeDefinitionBuilder.cs, VirtoCommerce.ExportModule.Data/packages.config, VirtoCommerce.ExportModule.JsonProvider/JsonExportProvider.cs, VirtoCommerce.ExportModule.JsonProvider/JsonProviderConfiguration.cs, VirtoCommerce.ExportModule.JsonProvider/ObjectDiscriminatorJsonConverter.cs, VirtoCommerce.ExportModule.JsonProvider/Properties/AssemblyInfo.cs, VirtoCommerce.ExportModule.JsonProvider/VirtoCommerce.ExportModule.JsonProvider.csproj, VirtoCommerce.ExportModule.JsonProvider/packages.config, VirtoCommerce.ExportModule.Tests/CsvExportProviderTests.cs, VirtoCommerce.ExportModule.Tests/JsonExportProviderTests.cs, VirtoCommerce.ExportModule.Tests/VirtoCommerce.ExportModule.Tests.csproj, VirtoCommerce.ExportModule.Web/BackgroundJobs/ExportJob.cs, VirtoCommerce.ExportModule.Web/Module.cs, VirtoCommerce.ExportModule.Web/Scripts/blades/export-settings.js, VirtoCommerce.ExportModule.Web/Scripts/services/generic-viewer-item-service.js, VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, VirtoCommerce.ExportModule.Web/module.manifest, VirtoCommerce.ExportModule.sln
Export/vp 297 move providers to separate projects (#532)
Changes for extended classes export support:
VP-299: Added "Export.General.FileNameTemplate" setting to manage export file name template.
Merge branch 'dev' into last_changes_from_v3
=> Last changes from v3

VirtoCommerce.ExportModule.Web/Scripts/blades/export-settings.js
remove isClosingDisabled: true
=> Cannot close the second level screen

VirtoCommerce.ExportModule.Core/VirtoCommerce.ExportModule.Core.csproj, VirtoCommerce.ExportModule.Core/packages.config, VirtoCommerce.ExportModule.CsvProvider/VirtoCommerce.ExportModule.CsvProvider.csproj, VirtoCommerce.ExportModule.CsvProvider/packages.config, VirtoCommerce.ExportModule.Data/VirtoCommerce.ExportModule.Data.csproj, VirtoCommerce.ExportModule.Data/packages.config, VirtoCommerce.ExportModule.JsonProvider/VirtoCommerce.ExportModule.JsonProvider.csproj, VirtoCommerce.ExportModule.JsonProvider/packages.config, VirtoCommerce.ExportModule.Tests/VirtoCommerce.ExportModule.Tests.csproj, VirtoCommerce.ExportModule.Tests/packages.config, VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, VirtoCommerce.ExportModule.Web/module.manifest, VirtoCommerce.ExportModule.Web/packages.config
downgrade platform version to 2.13.42
=> downgrade platform version

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-settings.js
Fill providers after getting exported type definitions;
=> VP-502: Fill providers after getting exported type definitions;

VirtoCommerce.ExportModule.Web/Scripts/blades/export-settings.js
use isAnyFilterApplied condition
=> vp-525 Remove inconsistencies in pricing export

src/VirtoCommerce.ExportModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3110
=> VP-3110: Fix logo

src/VirtoCommerce.ExportModule.Core/Model/ExportedTypeDefinition.cs, src/VirtoCommerce.ExportModule.Data/Extensions/ExportedTypeDefinitionBuilderExtensions.cs, src/VirtoCommerce.ExportModule.Web/Localizations/en.VirtoCommerce.Export.json, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.js, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.tpl.html, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-type-selector.js
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> #VP-4052 add restrict data select

src/VirtoCommerce.ExportModule.Web/Scripts/export.js
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> #VP-5269 search in menu

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.js
The algorithm for loading saved filters loads incorrect data into the binding model so the filter container trying to show an `undefined` value as a name parameter. 
Check data from the query, if this query doesn't contain the `name`  parameter skip assigning.
=> VP-5801: Prevent binding bad model

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer-filter.js
=> VP-6770: Replace panel action icons

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.js, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.tpl.html, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-progress.js, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-properties-selector.js, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-settings.js, src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-type-selector.js
=> VP-6768: Security section Replace Key icon

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer-filter.js
https://virtocommerce.atlassian.net/browse/PT-669
=> PT-670: Fix filter icon

src/VirtoCommerce.ExportModule.Web/BackgroundJobs/ExportJob.cs, src/VirtoCommerce.ExportModule.Web/BackgroundJobs/JobCancellationTokenWrapper.cs, src/VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, src/VirtoCommerce.ExportModule.Web/module.manifest
Reverts VirtoCommerce/vc-module-export#53
=> Revert "PT-777: Remove redundant class and update dependencies"

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-properties-selector.tpl.html, src/VirtoCommerce.ExportModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-799
=> PT-2629: Restyle properties selector

src/VirtoCommerce.ExportModule.Web/BackgroundJobs/ExportJob.cs
Remove redundant copy to the MemoryStream.
https://virtocommerce.atlassian.net/browse/PT-1910
=> PT-1910: Throw out copying into the MemoryStream in export

src/VirtoCommerce.ExportModule.Core/ModuleConstants.cs, src/VirtoCommerce.ExportModule.Web/Localizations/en.VirtoCommerce.Export.json, src/VirtoCommerce.ExportModule.Web/Module.cs, src/VirtoCommerce.ExportModule.Web/Scripts/export.js, src/VirtoCommerce.ExportModule.Web/module.manifest
=> PT-3859: Rename module to "Generic Export"

src/VirtoCommerce.ExportModule.CsvProvider/CsvExportProvider.cs, src/VirtoCommerce.ExportModule.CsvProvider/MetadataFilteredMap.cs, src/VirtoCommerce.ExportModule.CsvProvider/VirtoCommerce.ExportModule.CsvProvider.csproj
Update CsvHelper nuget package to latest versions
https://virtocommerce.atlassian.net/browse/PT-3918
=> PT-3918: Update CsvHelper nuget package to latest versions

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, src/VirtoCommerce.ExportModule.Core/VirtoCommerce.ExportModule.Core.csproj, src/VirtoCommerce.ExportModule.CsvProvider/VirtoCommerce.ExportModule.CsvProvider.csproj, src/VirtoCommerce.ExportModule.Data/VirtoCommerce.ExportModule.Data.csproj, src/VirtoCommerce.ExportModule.JsonProvider/VirtoCommerce.ExportModule.JsonProvider.csproj, src/VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, src/VirtoCommerce.ExportModule.Web/module.manifest, tests/VirtoCommerce.ExportModule.Tests/VirtoCommerce.ExportModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=> PT-1956: Bump .Net and EF up to 6

src/VirtoCommerce.ExportModule.Web/Controllers/Api/ExportController.cs
https://virtocommerce.atlassian.net/browse/PT-4907
https://virtocommerce.atlassian.net/browse/PT-4907
=> Redundant controller method is removed

src/VirtoCommerce.ExportModule.Web/Localizations/ru.VirtoCommerce.Export.json
=> Updated ru localization

src/VirtoCommerce.ExportModule.Core/VirtoCommerce.ExportModule.Core.csproj, src/VirtoCommerce.ExportModule.CsvProvider/MetadataFilteredMap.cs, src/VirtoCommerce.ExportModule.Data/Extensions/ExportDataQueryExtensions.cs, src/VirtoCommerce.ExportModule.Data/Extensions/ExportedTypeMetadataExtensions.cs, src/VirtoCommerce.ExportModule.Data/Security/AnyPolicyAuthorizationFilter.cs, src/VirtoCommerce.ExportModule.Data/Services/DataExporter.cs, src/VirtoCommerce.ExportModule.Data/Services/ExportedTypeDefinitionBuilder.cs, src/VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, src/VirtoCommerce.ExportModule.Web/module.manifest
- Add the ability to export enumerable exportable objects
=> Add the ability to export enumerable exportable objects

src/VirtoCommerce.ExportModule.Web/Controllers/Api/ExportController.cs, src/VirtoCommerce.ExportModule.Web/module.manifest, src/VirtoCommerce.ExportModule.Web/package-lock.json, src/VirtoCommerce.ExportModule.Web/package.json, src/VirtoCommerce.ExportModule.Web/webpack.config.js
fix: Rest API returns Unauthorized instead of Forbid.
https://virtocommerce.atlassian.net/browse/PT-12269
=> PT-12269: Rest API returns Unauthorized instead of Forbid.

.nuke, Directory.Build.props, src/VirtoCommerce.ExportModule.Core/VirtoCommerce.ExportModule.Core.csproj, src/VirtoCommerce.ExportModule.CsvProvider/CsvExportProvider.cs, src/VirtoCommerce.ExportModule.CsvProvider/VirtoCommerce.ExportModule.CsvProvider.csproj, src/VirtoCommerce.ExportModule.Data/Services/ExportFileStorage.cs, src/VirtoCommerce.ExportModule.Data/VirtoCommerce.ExportModule.Data.csproj, src/VirtoCommerce.ExportModule.JsonProvider/VirtoCommerce.ExportModule.JsonProvider.csproj, src/VirtoCommerce.ExportModule.Web/VirtoCommerce.ExportModule.Web.csproj, src/VirtoCommerce.ExportModule.Web/module.manifest, tests/VirtoCommerce.ExportModule.Tests/VirtoCommerce.ExportModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Export_3.800.0-pr-84-b84f.zip
=> PT-14740: update to .NET8

src/VirtoCommerce.ExportModule.Web/Scripts/blades/export-generic-viewer.tpl.html
feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Export_3.802.0-pr-86-56e9.zip
=> VCST-972: Remove Counter from Search panel
